version: "2"
run:
  tests: true
linters:
  default: none
  enable:
    - misspell
    - gosec
  settings:
    gosec:
      excludes:
        - G104
        - G401
        - G501
    misspell:
      locale: US
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - gosec
